[package]
name = "tankwart"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
url = "2.5"
reqwest = { version = "0.13.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.18"
dotenvy = "0.15"
